"use client";

import { Dialog, DialogContent, DialogFooter, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Printer } from "lucide-react";
import { format } from "date-fns";

export function InvoiceModal({ booking, open, onOpenChange }: { booking: any, open: boolean, onOpenChange: (open: boolean) => void }) {
  if (!booking) return null;

  const date = new Date(booking.start_time);
  const student = booking.student || {};
  const rate = student.hourly_rate || 70; 
  const amount = booking.duration * rate;
  const invoiceId = `INV-${format(date, "yyyyMMdd")}-${booking.id.slice(0, 4).toUpperCase()}`;

  const handlePrint = () => {
    window.print();
  };

  // --- 抽取发票内容为独立组件 (InvoiceTemplate) ---
  const InvoiceTemplate = () => (
    <div className="bg-white text-slate-900 p-8 h-full">
      {/* Header */}
      <div className="flex justify-between items-start mb-8 border-b border-slate-100 pb-6">
        <div>
          <h1 className="text-3xl font-black text-indigo-600 tracking-tight">INVOICE</h1>
          <p className="text-sm text-slate-400 mt-1 font-medium">#{invoiceId}</p>
        </div>
        <div className="text-right text-sm text-slate-500">
          <p className="font-bold text-slate-900">CuS Academy</p>
          <p>{format(new Date(), "dd MMM, yyyy")}</p>
        </div>
      </div>

      {/* Bill To */}
      <div className="mb-8">
        <p className="text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-2">Bill To (客户)</p>
        <h2 className="text-xl font-bold text-slate-900">{student.name}</h2>
        <p className="text-sm text-slate-500">{student.student_code ? `ID: ${student.student_code}` : ''}</p>
      </div>

      {/* Table */}
      <table className="w-full mb-8">
        <thead>
          <tr className="border-b border-slate-100 text-left text-[10px] font-bold text-slate-400 uppercase tracking-wider">
            <th className="pb-2">Description</th>
            <th className="pb-2 text-right">Hrs</th>
            <th className="pb-2 text-right">Rate</th>
            <th className="pb-2 text-right">Amount</th>
          </tr>
        </thead>
        <tbody>
          <tr className="text-sm font-medium text-slate-700">
            <td className="py-4 border-b border-slate-50">
              <p className="font-bold text-slate-900">Private Tutoring - {student.subject || "General"}</p>
              <p className="text-slate-400 text-xs mt-0.5">
                {format(date, "MMM d, yyyy")} | {format(date, "HH:mm")} - {format(new Date(booking.end_time), "HH:mm")}
              </p>
            </td>
            <td className="py-4 border-b border-slate-50 text-right">{booking.duration}</td>
            <td className="py-4 border-b border-slate-50 text-right">${rate}</td>
            <td className="py-4 border-b border-slate-50 text-right font-bold text-slate-900">${amount}</td>
          </tr>
        </tbody>
      </table>

      {/* Total */}
      <div className="flex justify-end mb-4">
        <div className="w-1/2">
          <div className="flex justify-between py-2 border-b border-slate-100 text-slate-500 text-sm">
            <span>Subtotal</span><span>${amount}</span>
          </div>
          <div className="flex justify-between py-3 text-lg">
            <span className="font-bold text-slate-900">Total</span>
            <span className="font-black text-indigo-600">${amount}</span>
          </div>
        </div>
      </div>
      
      <div className="text-center text-[10px] text-slate-300 pt-8 mt-auto">
        Generated by Tangent ERP
      </div>
    </div>
  );

  return (
    <>
      {/* 1. 正常的弹窗 (屏幕可见) */}
      <Dialog open={open} onOpenChange={onOpenChange}>
        <DialogContent className="max-w-2xl p-0 overflow-hidden bg-white gap-0 sm:rounded-lg print:hidden">
          <DialogTitle className="sr-only">Invoice Preview</DialogTitle>
          
          <InvoiceTemplate />

          <DialogFooter className="bg-slate-50 p-4 border-t border-slate-100 flex-row justify-end gap-2">
            <Button variant="outline" onClick={() => onOpenChange(false)}>Close</Button>
            <Button onClick={handlePrint} className="bg-indigo-600 hover:bg-indigo-700 text-white gap-2">
              <Printer className="h-4 w-4" /> 打印 / 保存 PDF
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* 2. 隐形的打印专用层 (屏幕不可见，仅打印时显示) */}
      <div className="hidden print:block print:fixed print:inset-0 print:bg-white print:z-[99999] print:h-screen print:w-screen print:overflow-visible">
         <InvoiceTemplate />
      </div>

      {/* 3. 强力 CSS 重置，确保打印时隐藏其他所有元素 */}
      <style jsx global>{`
        @media print {
          /* 隐藏除了 body 以外的所有根级元素，防止双重滚动条或背景 */
          body > *:not(.print\\:block) {
            display: none !important;
          }
          /* 确保打印层可见 */
          .print\\:block {
            display: block !important;
          }
          /* 移除页边距，让我们的 div 充满纸张 */
          @page {
            margin: 0; 
            size: auto;
          }
          body {
            margin: 0;
            padding: 0;
            background: white;
          }
        }
      `}</style>
    </>
  );
}